CREATE TABLE bus_timetabling.times_tables
(
    times_table_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_id       BIGINT NOT NULL,
    route_id     BIGINT NOT NULL,
    stop_id      BIGINT NOT NULL,
    arrival      TIME WITHOUT TIME ZONE,
    departure    TIME WITHOUT TIME ZONE,
    CONSTRAINT pk_timetables PRIMARY KEY (times_table_id),
    CONSTRAINT fk_timetables_bus FOREIGN KEY (bus_id) REFERENCES bus_timetabling.buses (bus_id),
    CONSTRAINT fk_timetables_route FOREIGN KEY (route_id) REFERENCES bus_timetabling.routes (route_id),
    CONSTRAINT fk_timetables_stop FOREIGN KEY (stop_id) REFERENCES bus_timetabling.stops (stop_id)
);

CREATE TABLE bus_timetabling.route_stops
(
    route_id BIGINT NOT NULL,
    stop_id  BIGINT NOT NULL,
    stop_num INTEGER NOT NULL,
    CONSTRAINT pk_route_stops PRIMARY KEY (route_id, stop_num),
    CONSTRAINT fk_route_stops_route FOREIGN KEY (route_id) REFERENCES bus_timetabling.routes (route_id),
    CONSTRAINT fk_route_stops_stop FOREIGN KEY (stop_id) REFERENCES bus_timetabling.stops (stop_id)
);

CREATE TABLE bus_timetabling.buses
(
    bus_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_number VARCHAR(255) NOT NULL,
    status     VARCHAR(255),
    route_id   BIGINT,
    CONSTRAINT pk_buses PRIMARY KEY (bus_id),
    CONSTRAINT fk_buses_route FOREIGN KEY (route_id) REFERENCES bus_timetabling.routes (route_id)
);

CREATE TABLE bus_timetabling.stops
(
    stop_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_stops PRIMARY KEY (stop_id)
);

CREATE TABLE bus_timetabling.routes
(
    route_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_name VARCHAR(255) NOT NULL,
    distance   DOUBLE PRECISION,
    CONSTRAINT pk_routes PRIMARY KEY (route_id)
);

