CREATE TABLE bus_timetabling.bus_route_manager
(
    bus_route_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_bus_route_manager PRIMARY KEY (bus_route_id)
);

CREATE TABLE bus_timetabling.buses
(
    bus_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    bus_number   VARCHAR(255),
    status       VARCHAR(255),
    bus_route_id BIGINT,
    CONSTRAINT pk_buses PRIMARY KEY (bus_id)
);

CREATE TABLE bus_timetabling.route_stop_schedule
(
    route_stop_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_num      INTEGER,
    route_id      BIGINT,
    CONSTRAINT pk_route_stop_schedule PRIMARY KEY (route_stop_id)
);

CREATE TABLE bus_timetabling.routes
(
    route_id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    route_name    VARCHAR(255),
    distance      DOUBLE PRECISION,
    route_stop_id BIGINT,
    bus_route_id  BIGINT,
    CONSTRAINT pk_routes PRIMARY KEY (route_id)
);

CREATE TABLE bus_timetabling.stops
(
    stop_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    stop_name     VARCHAR(255),
    route_stop_id BIGINT,
    CONSTRAINT pk_stops PRIMARY KEY (stop_id)
);

CREATE TABLE bus_timetabling.times_tables
(
    times_table_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_stop_id   BIGINT                                  NOT NULL,
    to_stop_id     BIGINT                                  NOT NULL,
    departure      time WITHOUT TIME ZONE,
    arrival        time WITHOUT TIME ZONE,
    bus_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_times_tables PRIMARY KEY (times_table_id)
);

ALTER TABLE bus_timetabling.buses
    ADD CONSTRAINT FK_BUSES_ON_BUS_ROUTE FOREIGN KEY (bus_route_id) REFERENCES bus_timetabling.bus_route_manager (bus_route_id);

ALTER TABLE bus_timetabling.routes
    ADD CONSTRAINT FK_ROUTES_ON_BUS_ROUTE FOREIGN KEY (bus_route_id) REFERENCES bus_timetabling.bus_route_manager (bus_route_id);

ALTER TABLE bus_timetabling.routes
    ADD CONSTRAINT FK_ROUTES_ON_ROUTE_STOP FOREIGN KEY (route_stop_id) REFERENCES bus_timetabling.route_stop_schedule (route_stop_id);

ALTER TABLE bus_timetabling.route_stop_schedule
    ADD CONSTRAINT FK_ROUTE_STOP_SCHEDULE_ON_ROUTE FOREIGN KEY (route_id) REFERENCES bus_timetabling.routes (route_id);

ALTER TABLE bus_timetabling.stops
    ADD CONSTRAINT FK_STOPS_ON_ROUTE_STOP FOREIGN KEY (route_stop_id) REFERENCES bus_timetabling.route_stop_schedule (route_stop_id);

ALTER TABLE bus_timetabling.times_tables
    ADD CONSTRAINT FK_TIMES_TABLES_ON_BUS FOREIGN KEY (bus_id) REFERENCES bus_timetabling.buses (bus_id);

ALTER TABLE bus_timetabling.times_tables
    ADD CONSTRAINT FK_TIMES_TABLES_ON_FROM_STOP FOREIGN KEY (from_stop_id) REFERENCES bus_timetabling.stops (stop_id);

ALTER TABLE bus_timetabling.times_tables
    ADD CONSTRAINT FK_TIMES_TABLES_ON_TO_STOP FOREIGN KEY (to_stop_id) REFERENCES bus_timetabling.stops (stop_id);